name: publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Resetting git to master
        run: git reset --hard master

      - name: Resetting git to master
        run: git fetch --unshallow --tags || true

      - name: Install poetry
        run: python3 -m pip install poetry

      - name: Install poem-plugins
        run: poetry self add poem-plugins

      - name: Install package
        run: poetry install

      - name: Publishing to pypi
        run: poetry publish --build --skip-existing
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}

      - name: Store built version
        run: echo "VERSION=$(poetry version --short)"


      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          repository: alvassin/yatracker-linker
          tags: ${{ env.VERSION }}
