name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pylama:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - run: python -m pip install poetry
      - run: poetry install
      - run: poetry check -q
      - run: poetry run pylama .
        env:
          FORCE_COLOR: 1
      - run: poetry run unify --quote "'" --check-only --recursive yatracker_gitlab_linker tests
        env:
          FORCE_COLOR: 1
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - run: python -m pip install poetry
      - run: poetry install
      - run: poetry run mypy --install-types --non-interactive yatracker_gitlab_linker/
        env:
          FORCE_COLOR: 1

  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        python:
          - '3.11'
    steps:
      - uses: actions/checkout@v2
      - name: Setup python${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
      - run: python -m pip install poetry
      - run: poetry install --with=uvloop
      - run: >-
          poetry run pytest \
            -vv \
            --cov=yatracker_gitlab_linker \
            --cov-report=term-missing \
            --aiomisc-test-timeout=120 \
            tests
        env:
          FORCE_COLOR: 1
      - run: poetry run coveralls
        env:
          COVERALLS_PARALLEL: 'true'
          COVERALLS_SERVICE_NAME: github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finish:
    needs:
       - tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
